options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 🔧 Build frontend
  - name: 'node:20-slim'
    entrypoint: 'bash'
    dir: 'frontend'
    args:
      - '-c'
      - |
        npm install && npm run build

  # 🐳 Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-api', '.']

  # 📤 Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-api']

  # 🚀 Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MONGO_URI=mongodb+srv://fiyaz7214:Hamsa1234@cluster0.8huw80x.mongodb.net/leads2opp?retryWrites=true&w=majority&appName=Cluster0'
      - 'TWILIO_AUTH_TOKEN=d1164435f230520ddfc03eb3b1dbe125'
      - 'TWILIO_PHONE_NUMBER=+15392528842'

images:
  - 'gcr.io/$PROJECT_ID/backend-api'
