options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'node:20-slim'
    entrypoint: 'bash'
    dir: 'frontend'
    args:
      - '-c'
      - |
        npm install && npm run build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - backend-api
      - --image
      - gcr.io/$PROJECT_ID/backend-api
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --update-secrets
      - FIREBASE_CONFIG=firebase-config:latest
      - --command
      - node
      - --args
      - backend/server.js
